### ISSUE TITLE
Images in How it works section are not displaying

### ISSUE THREAD

**Issue by Karthik-59** [cyboholics/portfolioshop#180]
**Describe the bug**
As we can see in the screenshot, the images are not displaying.

**To Reproduce**
1. Go to public folder
2. Click on productHowItWorks1.svg (similarly other 2 images)
3. See error

**Expected behavior**
Images to be displayed, in 'how it works' section

**Screenshots**
![image1](https://user-images.githubusercontent.com/77478622/198261946-d174bc2e-6b00-4ca3-ab8d-f5b3056a5fe7.png)

**Desktop**
 - OS: Windows
 - Browser Chrome
 - Version 106.0.5249.119

**Additional context**
I would like to work on this issue if you assign me.

**Comment by sudip-mondal-2002** [comment]
We'll look into it. Would you like to work on it?

**Comment by Atharvp01** [comment]
Hey, Sudip 👋 I would like to work on this issue I know what's happening here.

**Comment by sudip-mondal-2002** [comment]
Hey, sure, please fork the repository and create a PR when done. Thanks for connecting:)

**Comment by Atharvp01** [comment]
hey, @sudip-mondal-2002 I got one lighthouse CI check fail on the pr i made, do you know how can I fix it? i think it's because of the node version

**Comment by sudip-mondal-2002** [comment]
Ignore that for now. Don't worry, I will merge it.

**Comment by Atharvp01** [comment]
Okay
